name: Branch Injection PoC

on:
  pull_request:

jobs:
  poc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Vulnerable Step (Command Injection)
        run: |
          echo Deploying branch ${{ github.head_ref }}
